// Primitive data types in JavaScript include:

//  1. Numbers - Integers, floats
//  2. Strings - Any data under single quote, double quote or backtick quote
//  3. Booleans - true or false value
//  4. Null - empty value or no value
//  5. Undefined - a declared variable without a value
//  6. Symbol - A unique value that can be generated by Symbol constructor



//String data types
let space = ' ' // an empty space string
let firstName = 'John';
let lastName = 'Smith';
let country = 'India';
let city = 'Bengaluru';
let language = 'JavaScript';
let job = 'Employee';

let age  = 26;
// Concatenation using additional operator 
let fullName = firstName + space + lastName ;
console.log(fullName);
let info = fullName + '.I am ' + age +'.I live in ' + country ;
console.log(info);

// template literals 
let personalInfo = `I am ${fullName}.I am ${age} year old. I live in ${country}`;
console.log(personalInfo);
// string interpolation 
let userPersonInfo = `I am ${fullName}. I live in ${city}, ${country}. I am a ${job}. The Programming language I know ${language}.`;
console.log(userPersonInfo);




//Number data types

const gravity = 9.81; //const is use for non changing value
const PI = 3.14; 
// const use for non changing variable which we use as constant


// Some examples 

let word = 'JavaScript' //string data type
// we dont' modify string 
// we don't do like this, word[0] = 'Y' 
let numOne = 3; //number data types
let numTwo = 7;
console.log(numOne == numTwo) ;     // true

let num1 = 6;
let num2 = 6;
console.log(num1 == num2) //true

let js = 'JavaScript';
let py = 'Python';
console.log(js == py)             //false 

let lightOn = true;  //boolean
let lightOff = false;
console.log(lightOn == lightOff) // false